force-app/main/default/objects/DistributedStateTransformation__c/DistributedStateTransformation__c.object-meta.xml
<CustomObject>
    <label>Distributed State Transformation</label>
    <nameField>
        <label>Distributed State Transformatio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributed State Transformations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyTransformation__c/PropertyTransformation__c.object-meta.xml
<CustomObject>
    <label>Property Transformation</label>
    <nameField>
        <label>Attribute Transformation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Transformations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyTransformation__c/fields/DistributedStateTransformation__c.field-meta.xml
<CustomField>
    <fullName>DistributedStateTransformation__c</fullName>
    <label>Distributed State Transformation</label>
    <referenceTo>DistributedStateTransformation__c</referenceTo>
    <relationshipLabel>Property Transformations</relationshipLabel>
    <relationshipName>PropertyTransformations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/IsDynamic__c.field-meta.xml
<CustomField>
    <fullName>IsDynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dynamic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/SourcePropertyName__c.field-meta.xml
<CustomField>
    <fullName>SourcePropertyName__c</fullName>
    <label>Source Property Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/SourceValue__c.field-meta.xml
<CustomField>
    <fullName>SourceValue__c</fullName>
    <label>Source Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/TargetPropertyName__c.field-meta.xml
<CustomField>
    <fullName>TargetPropertyName__c</fullName>
    <label>Target Property Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/TargetValue__c.field-meta.xml
<CustomField>
    <fullName>TargetValue__c</fullName>
    <label>Target Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DistributedStateTransformation.cls
/*
 * Author: oliver.preuschl
 */

public with sharing class DistributedStateTransformation {
  @AuraEnabled(cacheable=true)
  public static List<PropertyTransformation__c> getPropertyTransformationsByName(
    String name
  ) {
    return [
      SELECT
        Id,
        SourcePropertyName__c,
        TargetPropertyName__c,
        SourceValue__c,
        TargetValue__c,
        IsDynamic__c
      FROM PropertyTransformation__c
      WHERE DistributedStateTransformation__r.Name = :name
    ];
  }
}