force-app/main/default/objects/DistributedStateTransformation__c/DistributedStateTransformation__c.object-meta.xml
<CustomObject>
    <label>Distributed State Transformation</label>
    <nameField>
        <label>Distributed State Transformatio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributed State Transformations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyTransformation__c/PropertyTransformation__c.object-meta.xml
<CustomObject>
    <label>Property Transformation</label>
    <nameField>
        <label>Attribute Transformation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Transformations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyTransformation__c/fields/DistributedStateTransformation__c.field-meta.xml
<CustomField>
    <fullName>DistributedStateTransformation__c</fullName>
    <label>Distributed State Transformation</label>
    <referenceTo>DistributedStateTransformation__c</referenceTo>
    <relationshipLabel>Property Transformations</relationshipLabel>
    <relationshipName>PropertyTransformations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/IsDynamic__c.field-meta.xml
<CustomField>
    <fullName>IsDynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dynamic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/SourcePropertyName__c.field-meta.xml
<CustomField>
    <fullName>SourcePropertyName__c</fullName>
    <label>Source Property Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/SourceValue__c.field-meta.xml
<CustomField>
    <fullName>SourceValue__c</fullName>
    <label>Source Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/TargetPropertyName__c.field-meta.xml
<CustomField>
    <fullName>TargetPropertyName__c</fullName>
    <label>Target Property Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyTransformation__c/fields/TargetValue__c.field-meta.xml
<CustomField>
    <fullName>TargetValue__c</fullName>
    <label>Target Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DistributedStateTransformation_T.cls
/**
 * @author  : Oliver Preuschl
 * Modifications Log
 * Ver   Date         Author            Modification
 * 1.0   10-03-2020   Oliver Preuschl   Initial Version
 **/
@IsTest
public with sharing class DistributedStateTransformation_T {
  @TestSetup
  static void createTestRecords() {
    DistributedStateTransformation__c accountChildTableTransformation = new DistributedStateTransformation__c(
      Name = 'AccountChildDataTable'
    );
    insert (accountChildTableTransformation);
    List<PropertyTransformation__c> propertyTransformations = new List<PropertyTransformation__c>();
    PropertyTransformation__c opportunityDataTableFields = new PropertyTransformation__c(
      DistributedStateTransformation__c = accountChildTableTransformation.Id,
      Name = 'OpportunityDataTableTransformation',
      SourcePropertyName__c = 'accountChildSObjectName',
      SourceValue__c = 'Opportunity',
      TargetPropertyName__c = 'accountChildDataTableFields',
      TargetValue__c = 'Name,StageName,Amount,CloseDate',
      IsDynamic__c = false
    );
    propertyTransformations.add(opportunityDataTableFields);
    PropertyTransformation__c caseDataTableFields = new PropertyTransformation__c(
      DistributedStateTransformation__c = accountChildTableTransformation.Id,
      Name = 'OpportunityDataTableTransformation',
      SourcePropertyName__c = 'accountChildSObjectName',
      SourceValue__c = 'Case',
      TargetPropertyName__c = 'accountChildDataTableFields',
      TargetValue__c = 'Subject,Type,CaseReasong,Status,Origin,Priority,Contact',
      IsDynamic__c = false
    );
    propertyTransformations.add(caseDataTableFields);
    insert (propertyTransformations);
  }

  @IsTest
  static void givenDistributedStateTransformationWhenRequestingThenItIsReturned() {
    //Given
    //When
    Test.startTest();
    List<PropertyTransformation__c> propertyTransformations = DistributedStateTransformation.getPropertyTransformationsByName(
      'AccountChildDataTable'
    );
    Test.stopTest();
    //Then
    System.assertEquals(2, propertyTransformations.size());
  }
}